name: Verify and minify (on pushes)
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, edited]  
  workflow_dispatch:
jobs:
  verify:
    name: Verify CSS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.0.2  
      - run: npm -g i csstree-validator
      - name: Verify CSS
        run: bash ./verify.sh
  minify:
    runs-on: ubuntu-22.04
    name: Minify CSS
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4.0.2  
      - run: npm -g i minify
      - name: Minify CSS
        run: bash ./minify.sh
      - name: Set Git User Info
        run: bash -c 'git config --global user.name "some-css bot"; git config --global user.email "some-css.bot@majlitech.pl"'
      - name: Authenticate to git
        run: echo https://majlitech:${{ secrets.GITHUB_TOKEN }}@github.com > ~/.git-credentials
      - name: Push to repo
        run: bash -c "git add min-css; git commit -m 'Minified CSS ($(echo "{{ github.sha }}" | head -c 7))'; git push"
# <waiting for response from w3c (https://github.com/w3c/css-validator/issues/413)>
