name: Verify and minify (on pushes)
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, edited]  
  workflow_dispatch:
jobs:
  cache-packages:
    name: Cache packages
    runs-on: ubuntu-22.04
    steps:
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - uses: actions/setup-node@v4.0.2  
      - run:  npm -i minify csstree-validator
  verify:
    name: Verify CSS
    runs-on: ubuntu-22.04
    needs: [cache-packages]
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - uses: actions/setup-node@v4.0.2  
      - name: Verify CSS
        run: bash ./verify.sh
  minify:
    runs-on: ubuntu-22.04
    name: Minify CSS
    needs: [verify, cache-packages]
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - uses: actions/setup-node@v4.0.2  
      - name: Minify CSS
        run: bash ./minify.sh
# <waiting for response from w3c (https://github.com/w3c/css-validator/issues/413)>
