on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, edited]
  workflow_dispatch:
jobs:
  verify:
    name: Verify CSS
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Cache npm packages
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-npm-${{ hashFiles('package*.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-npm-
      - uses: actions/setup-node@v4.0.2  
      - name: Install csstree-validator
        run: npm install -g csstree-validator
      - name: Verify CSS
        run: bash ./verify.sh
# <waiting for response from w3c (https://github.com/w3c/css-validator/issues/413)>
